### ISSUE TITLE
Fix UI/UX

### ISSUE THREAD

**Issue by cewing** [collective/Products.PloneKeywordManager#14]
the control panel is a bit confusing to use.  We need to get in line with more modern approaches and clean it up.  One idea is to only allow for the selection of primary key matches and to provide the list of nearest matches as information only.  this would likely help.

**Comment by hvelarde** [comment]
@agnogueira comments?

**Comment by CorySanin** [comment]
#26 aims to address this, as I felt the same way.

**Comment by CorySanin** [comment]
#26 got merged. Yay!
