### ISSUE TITLE
Large keyword count is problematic

### ISSUE THREAD

**Issue by cewing** [collective/Products.PloneKeywordManager#17]
For sites with very very large numbers of keywords, the control panel really has problems.  Better data structures and Pagination would really be a great help.

**Comment by tobiasherp** [comment]
I like to second that. I have a site with hunderts of (unused; see #39) keywords, and it is quite irritating; the page reloads sometimes in surprising situations.
To suggest a possible improvent: perhaps we could reload only the needed parts, by AJAX requests?

**Comment by tobiasherp** [comment]
> @tobiasherp hundreds?

Uh, yes; sorry! :-)

**Comment by flipmcf** [comment]
OMG This is closing!
