### ISSUE TITLE
Search (Magnifier Icon) ignores selected index

### ISSUE THREAD

**Issue by jensens** [collective/Products.PloneKeywordManager#23]
Clicking on the magnifier icon there is always the Subject index searched and the prior selected index is ignored.
![screenshot from 2017-06-08 10 43 35](https://user-images.githubusercontent.com/157140/26919872-6da1c3f2-4c37-11e7-9894-2b1bb13f89d4.png)
![screenshot from 2017-06-08 10 43 59](https://user-images.githubusercontent.com/157140/26919881-71ed1e52-4c37-11e7-84d2-a555ea97b423.png)

**Comment by jensens** [comment]
@petschki was this fixed by 0eaa6533ec11df6a45e66ae6e71cdcdbf1b957ca ?

**Comment by petschki** [comment]
fixed and merged here https://github.com/collective/Products.PloneKeywordManager/pull/20

**Comment by petschki** [comment]
unfortunately unreleased until now 😢

**Comment by jensens** [comment]
done https://pypi.org/project/Products.PloneKeywordManager/2.2.1/
