### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by serge73** [collective/Products.PloneKeywordManager#32]
The add-on does not work with languages other than English (Latin letters). For testing, I used Russian.

Plone 5.2.0 (5207)
CMF 2.4.0
Zope 4.1.1
Python 2.7.16 (default, Apr 6 2019, 01:42:57) [GCC 8.3.0]
PIL 6.1.0 (Pillow)
WSGI: Вкл.
Сервер: waitress 1.3.0

Products.PloneKeywordManager-3.0.2-py2.7.egg

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module Products.PloneKeywordManager.browser.prefs_keywords_view, line 51, in __call__
  Module Products.PloneKeywordManager.browser.prefs_keywords_view, line 77, in changeKeywords
  Module Products.PloneKeywordManager.browser.prefs_keywords_view, line 101, in doReturn
  Module Products.CMFPlone.PloneTool, line 580, in addPortalMessage
  Module Products.statusmessages.adapter, line 36, in add
  Module zope.i18n, line 194, in translate
  Module zope.i18n.translationdomain, line 85, in translate
  Module zope.i18n.translationdomain, line 165, in _recursive_translate
  Module zope.i18n, line 244, in interpolate
  Module zope.i18n, line 239, in replace
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)
```

**Comment by jensens** [comment]
in Python 2.7 the `addPortalMessage` and `logger.info(...` in `doReturn` probably get a `str` instead of `unicode`. My hotfix by commenting line 101 and 103 in `Products.PloneKeywordManager-3.0.2-py2.7.egg/Products/PloneKeywordManager/browser/prefs_keywords_view.py` fixes it (but no message is shown).

**Comment by flipmcf** [comment]
This is related to #53  We need to apply a bit of a better fix.

**Comment by flipmcf** [comment]
This is only for python 2.7 ?   I'm seeing good behavior on Python 3  (3.8.10 )

![keyword-mgr-replace](https://user-images.githubusercontent.com/1752883/144288707-17897fbc-94db-4fd5-861b-70674b9c22ea.png)

**Comment by jensens** [comment]
So we go for a major and drop Python 3? I am all in.

**Comment by flipmcf** [comment]
I would hope @serge73 is ok with maintaining a Python 2.7 branch if they really need it.

**Comment by jensens** [comment]
a major version bump and a branch is always fine.

**Comment by flipmcf** [comment]
> a major version bump and a branch is always fine.
So, you thinking PKM 4.0.0 ?

**Comment by flipmcf** [comment]
If a version 3.0.3 is cut, this can close.
