### ISSUE TITLE
Delete all unused keywords in a site

### ISSUE THREAD

**Issue by tobiasherp** [collective/Products.PloneKeywordManager#39]
I have a Plone 4 site where a colleague of mine installed Products.PloneKeywordManager v2.1 years ago and created hundreds of keywords which might have been useful but have never been actually used.

Now, to start actually using it, we'd like to have **a handy short list** of keywords (which will then eventually grow as needed, of course).

It seems to me, the _only_ suggested way to delete keywords is: select one or more keywords, and replace them by another one.

This makes sense for _actually used_ keywords, but it is no solution for my situation where _nearly all keywords are unused._

So, here is my feature request:
**Could we please have a facility to (list and) delete all unused keywords?**

If it exists in the Plone-5-only v3 branch -- could it be merged back to v2?

Thank you!

**Comment by tobiasherp** [comment]
@flipmcf :
> I think if you drop and re-index the keyword index, you will remove all the unused keywords.

Ah, interesting.
In my case, I made a list of all used subjects, and then removed them by hand somehow (IIRC).
However, it seems somewhat suboptimal to reindex the whole site just to get rid of unused values, while all needed information could be taken from the catalog instead.

**Comment by flipmcf** [comment]
I couldn't recreate this issue during my tests.

I created keywords (by editing content and adding new terms to 'subject').

i then used the keyword manager to delete the keywords.  They disappeared from the index and were not available as auto-complete options on my subject field.

The only reason there would be a keyword in a keyword index is there are objects that are indexed with that value.

The concept of an 'unused keyword' is confusing to me.  there must be objects using the keyword if they appear in the index.

**Comment by flipmcf** [comment]
I may have unintentionally fixed this bug - if we look at it another way:

https://github.com/collective/Products.PloneKeywordManager/issues/61

Was that the issue?

**Comment by flipmcf** [comment]
I shouldn't have closed this.   It's asking for the delete to be backported

**Comment by gforcada** [comment]
On the control panel there is a way to select tags and remove them 👍🏾
