### ISSUE TITLE
When similar keywords are displayed, search should link to the corresponding keyword

### ISSUE THREAD

**Issue by abl123** [collective/Products.PloneKeywordManager#67]
Using Products.PloneKeywordManager 4.0.0.

When the "Show similar keywords" option is selected, the Search icon next to each similar keyword links to a search for the Initial keyword, not the similar keyword.  

Ex: If the keyword is "Plone" and the similar keywords are "Plone 4" and "Plone 5".  I would expect the search icon next to "Plone 4" to open a search for "Plone 4", but instead it searches for "Plone".

Steps to reproduce:

1. Go to {site_root}/prefs_keywords_view
2. In "Search by Keyword" input, search for "Plone"
3. After results are displayed, check "Show similar keywords" box (at the top)
4. Click the search icon next to each keyword displayed

In each row, all the search icons search for the same keyword, regardless of the label.

**Comment by flipmcf** [comment]
I'm fixing lots of bugs today in KeywordManager .  I will see if I can squeeze this one in too.   Our users will complain about this too once it's in use.

**Comment by flipmcf** [comment]
Bad Github.  Merging to my local fork does not close this issue!

**Comment by flipmcf** [comment]
This is the pull request that is getting a review.  

https://github.com/collective/Products.PloneKeywordManager/pull/72

It's a very, very simple change, so we should see the PR approved very soon.

**Comment by flipmcf** [comment]
I have no social skills.  Only technical skills.   It took me this long to notice.

HI ANNETTE!
