### ISSUE TITLE
Provide utility functions to allow scripting

### ISSUE THREAD

**Issue by gforcada** [collective/Products.PloneKeywordManager#74]
We have a Plone website with +80k tags. Lots of them are user generated, so the quality and usefulness of them is quite questionable 😓 

We are in the process of cleaning that up, and it would be really useful if this package would provide basic functions, out of views to merge two/three/four/... tags together, or extract tags that are similar on a csv/json file of the sorts ✨ 

The UI on this package is great, but can not really scale to such big numbers, it is far easier to do an extraction of tags, get someone figure out how that should be merged and get a csv-like file back with the merging operations to perform.

Once the first big clean up happens, sure, keeping the quality of the tags within the UI, and rename a few tags now and then is perfectly fine.

If it is already possible, sorry for the noise 😅

**Comment by djay** [comment]
One way to solve this is with collective.exportimport but the output is Json so not so end user friendly. 
The goals of collective.importexport was to make a end user friendly way to make such bulk changes. Doing it via CSV files. Perhaps one day that feature would be added to export import. But it's still not clear how to format a list like keywords inside a CSV. Perhaps Json is just as good? You can find and replace with a text editor.

**Comment by gforcada** [comment]
Thanks for the tip, but I don't think exporting +100k documents to work on the tags and later re-import all +100k of them is a good approach 😅

**Comment by gforcada** [comment]
With #75 it is a bit easier, kind of 👍🏾
