### ISSUE TITLE
CI broken for Plone 4.0

### ISSUE THREAD

**Issue by hvelarde** [collective/Products.PloneKeywordManager#8]
Continuous integration is currently broken for Plone 4.0 because of a mismatched version:

on Plone 4.0:

    Error: There is a version conflict.
    We already have: zope.schema 3.5.4
    but z3c.form 3.0.2 requires 'zope.schema>=3.6.0'.

we need to document how to  install PloneKeywordManager on Plone 4.0 or remove that version from the compatibility list.

**Comment by cewing** [comment]
4.0 and 4.1 are no longer listed as supported by classifier.  Tests still pass for 4.1, but README makes clear that this is not expected to work in less than 4.2

**Comment by hvelarde** [comment]
then we need to clean up the `.travis.yml` file
