### ISSUE TITLE
Version 5.0.0 target

### ISSUE THREAD

**Issue by petschki** [collective/Products.PloneKeywordManager#80]
I'm updating the management template to Plone 6 and Bootstrap 5 ... would it be OK if version 5,0 targets Plone 6 only or should there be Plone 5.2 compatibility too ... 

/cc @gforcada @jensens

**Comment by jensens** [comment]
cc @flipmcf 

For my projects it would be fine, I pinned them to current release already and would love to see this moving further forward.

**Comment by gforcada** [comment]
I would probably want to add a few features to it at some point and we are still on Plone 5.2, but we can push it upstream to be 6.0 compatible and backport it to our fork, if we still are on 5.2 😄

**Comment by petschki** [comment]
As mentioned here https://github.com/collective/Products.PloneKeywordManager/pull/81#issuecomment-1326010958 I've created a `5.x` branch before merging the `plone6` changes. Does someone of you want to make a `6.0.0` release or give me an invite on pypi?

**Comment by jensens** [comment]
> As mentioned here [#81 (comment)](https://github.com/collective/Products.PloneKeywordManager/pull/81#issuecomment-1326010958) I've created a `5.x` branch before merging the `plone6` changes. Does someone of you want to make a `6.0.0` release or give me an invite on pypi?

Invite sent!

**Comment by petschki** [comment]
@jensens sorry missed the invitation ... can u please send again?

**Comment by flipmcf** [comment]
We';re still on 5.2 also.  Are there 5.2 breaking features coming in any new PR's?

**Comment by petschki** [comment]
Released `6.0.0` which is for Plone 6+ only. Version `5.0.0` is on branch `5.x` now.
