### ISSUE TITLE
Error when tryng to open Keyword in 5.2.2

### ISSUE THREAD

**Issue by rileydog** [collective/Products.PloneKeywordManager#82]
My Action:  Installed (Products.PloneKeywordManager 3.0.2
My configuration:
Version Overview

    Plone 5.2.2 (5209)
    CMF 2.4.8
    Zope 4.5.1
    Python 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
    PIL 6.2.2 (Pillow)
    WSGI: On
    Server: waitress 1.4.4
===============================
Error Message:

We’re sorry, but there seems to be an error…

Here is the full error message:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 359, in publish_module
  Module ZPublisher.WSGIPublisher, line 254, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.PloneKeywordManager.browser.prefs_keywords_view, line 30, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 58, in __call__
  Module zope.pagetemplate.pagetemplate, line 133, in pt_render
  Module Products.PageTemplates.engine, line 367, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 307, in render
  Module chameleon.template, line 214, in render
  Module chameleon.utils, line 75, in raise_with_traceback
  Module chameleon.template, line 192, in render
  Module 3bf485c00acbcfc52d5a6ad7b9f4060b, line 2087, in render
  Module 4d4bd35e64d7d7933502ed748132966d, line 382, in render_master
  Module 5a91f82f687e0fa6fd77db1a76a28203, line 864, in render_master
  Module 4d4bd35e64d7d7933502ed748132966d, line 357, in __fill_content
  Module 5a91f82f687e0fa6fd77db1a76a28203, line 1526, in render_content
  Module 4d4bd35e64d7d7933502ed748132966d, line 343, in __fill_main
  Module 3bf485c00acbcfc52d5a6ad7b9f4060b, line 638, in __fill_prefs_configlet_main
chameleon.exc.ExpressionError: chameleon.exc.ExpressionError: $ must be doubled or followed by a simple path

 - String:     "$('.simkeywords').css('display', (this.checked)?'initial':'none')"
 - Filename:   /opt/plone/buildout-cache/eggs/Products.PloneKeywordManager-3.0.2-py3.8.egg/Products/PloneKeywordManager/browser/prefs_keywords_view.pt
 - Location:   (line 79: col 52)
 - Source:     ... $('.simkeywords').css('display', (this.checked)?'initial':'none') ...
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 - Expression: "provider:plone.abovecontent"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 67: col 59)
 - Source:     ... 
                                       ^
 - Expression: "context/@@main_template/macros/master"
 - Filename:   ... oducts/CMFPlone/skins/plone_prefs/prefs_main_template.pt
 - Location:   (line 2: col 30)
 - Source:     ... tal:use-macro="context/@@main_template/macros/master">
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "context/prefs_main_template/macros/master"
 - Filename:   ... ducts/PloneKeywordManager/browser/prefs_keywords_view.pt
 - Location:   (line 3: col 23)
 - Source:     ... l:use-macro="context/prefs_main_template/macros/master"
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7f4fa70cba90>
               options: {}
               args: ({},)
               nothing: None
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7f4fc97b6220>
               request: <WSGIRequest, URL=http://24.199.97.133:8080/Plone/prefs_keywords_view>
               view: <Products.Five.browser.metaconfigure.SimpleViewClass from /opt/plone/buildout-cache/eggs/Products.PloneKeywordManager-3.0.2-py3.8.egg/Products/PloneKeywordManager/browser/prefs_keywords_view.pt object at 0x7f4fa618a670>
               context: <PloneSite at /Plone>
               views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7f4fa70cb700>
               here: <PloneSite at /Plone>
               container: <PloneSite at /Plone>
               root: <Application at >
               traverse_subpath: []
               user: <PropertiedUser 'admin'>
               default: <DEFAULT>
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7f4fa7cd86c0>
               loop: {'fld': <Products.PageTemplates.engine.RepeatItem object at 0x7f4fa6defca0>}
               target_language: None
               translate: <function BaseTemplate.render.<locals>.translate at 0x7f4fa6984940>
               macroname: 'master'
               attrs: {}

The Plone® Open Source CMS/WCM is © 2000-2023 by the Plone Foundation and friends. Distributed under the GNU GPL license.
Powered by Plone & Python

    Site Map Accessibility Contact 

============================

**Comment by petschki** [comment]
duplication of https://github.com/collective/Products.PloneKeywordManager/issues/33 ... fixed in version `3.0.3`
