### ISSUE TITLE
ValueError: Subject is not a valid field

### ISSUE THREAD

**Issue by jnachtigall** [collective/Products.PloneKeywordManager#9]
Trying to open /prefs_keywords_view under Plone 4.2 results in the following traceback. (Do not know if related, but I use raptus.multilanguageplone also)

    Traceback (innermost last):
    Module ZPublisher.Publish, line 60, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 46, in call_object
    Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
    Module Products.CMFFormController.BaseControllerPageTemplate, line 31, in _call
    Module Shared.DC.Scripts.Bindings, line 322, in __call__
    Module Products.PloneHotfix20130618.spamProtect, line 35, in _patched_bindAndExec
    Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
    Module Products.CMFCore.FSPageTemplate, line 237, in _exec
    Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
    Module Products.PageTemplates.PageTemplate, line 79, in pt_render
    Module zope.pagetemplate.pagetemplate, line 113, in pt_render
    Module zope.tal.talinterpreter, line 271, in __call__
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 888, in do_useMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 888, in do_useMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 946, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 888, in do_useMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 946, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 946, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
    Module zope.tales.tales, line 696, in evaluate
    - URL: file:/usr/local/Plone/buildout-cache/eggs/Products.PloneKeywordManager-2.0-py2.7.egg/Products/PloneKeywordManager/skins/keyword_manager/prefs_keywords_view.cpt
    - Line 11, Column 0
    - Expression: <PythonExpr pkm.getKeywords(context=context,indexName=field)>
    - Names:
        {'container': <PloneSite at /mysite>,
        'context': <PloneSite at /mysite>,
        'default': <object object at 0x80155e4d0>,
        'here': <PloneSite at /mysite>,
        'loop': {},
        'nothing': None,
        'options': {'args': (),
                    'state': <Products.CMFFormController.ControllerState.ControllerState object at 0x827188910>},
        'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x82b8ae578>,
        'request': <HTTPRequest, URL=https://mysite.org/prefs_keywords_view>,
        'root': <Application at >,
        'template': <FSControllerPageTemplate at /mysite/prefs_keywords_view>,
        'traverse_subpath': [],
        'user': <PloneUser 'me'>}
    Module Products.PageTemplates.ZRPythonExpr, line 48, in __call__
    - __traceback_info__: pkm.getKeywords(context=context,indexName=field)
    Module PythonExpr, line 1, in <expression>
    Module Products.PloneKeywordManager.tool, line 144, in getKeywords
    ValueError: Subject is not a valid field

**Comment by cewing** [comment]
This issue is ancient, and I'm closing it

@jnachtigall if this is in fact still a problem, please re-open.
